USE [master];
GO

DELETE FROM dbo.UsuariosMirror;
DELETE FROM dbo.CursosMirror;
GO

INSERT INTO dbo.CursosMirror (IdCurso, Nombre, DuracionHoras, Activo) VALUES (undefined, 'Curso Admin', 100, 0);
INSERT INTO dbo.CursosMirror (IdCurso, Nombre, DuracionHoras, Activo) VALUES (undefined, 'Master Sistemas de aplicaciones Cloud', 100, 1);
INSERT INTO dbo.CursosMirror (IdCurso, Nombre, DuracionHoras, Activo) VALUES (undefined, 'Master Desarrollo de aplicaciones Cloud', 100, 0);
INSERT INTO dbo.CursosMirror (IdCurso, Nombre, DuracionHoras, Activo) VALUES (undefined, 'Master Sistemas', 100, 1);
INSERT INTO dbo.CursosMirror (IdCurso, Nombre, DuracionHoras, Activo) VALUES (undefined, 'Master Desarrollo Apps Cloud 2025-2026', 100, 1);
INSERT INTO dbo.CursosMirror (IdCurso, Nombre, DuracionHoras, Activo) VALUES (undefined, 'Big Data', 100, 1);
INSERT INTO dbo.CursosMirror (IdCurso, Nombre, DuracionHoras, Activo) VALUES (undefined, 'Master Desarrollo Pago 2025-2026', 100, 1);
INSERT INTO dbo.CursosMirror (IdCurso, Nombre, DuracionHoras, Activo) VALUES (undefined, 'IA y Big Data', 100, 1);

GO

INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Monica', 'Delgado Capellan', 'monicadelgado@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Rodrigo', 'Gonzalez', 'rodrigo@gmail.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alberto', 'de lope hernandez', 'alberto.delope@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Carolina', 'Penalba Corpa', 'carolina@gmail.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Ariadna', 'López Abalo', 'privatedari@gmail.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Paco', 'Garcia Serrano', 'paco.garcia.serrano@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Admin', 'Admin', 'admin@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Sofia', 'Martinez', 'sofia.martinez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Maki Spariva', 'Mirón Olona', 'makispariva.miron@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Manuel', 'Perez', 'manuel.perezbenavent@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Sofía', 'Villarejo Rodríguez', 'sofia.villarejo@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Andrei', 'Popa', 'andreidaniel.popa@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Jaime Jesús', 'Laguna Moreno', 'jaimejesus.laguna@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Doryan Alexandro', 'Mamani Ticona', 'doryanalexandro.mamani@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Ariadna', 'López Abalo', 'ariadna.lopez@tajamar365.com', 0, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Gabriel', 'Fonseca', 'gabrielalejandro.fonseca@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Amanda', 'Crespo Luis', 'amanda.crespo@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Daniel', 'Rodríguez Lancha', 'daniel.rodriguezlancha@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Rodrigo', 'González Orovio', 'rodrigo.gonzalezorovio@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Jorge', 'Ruiz Parra', 'jorge.ruiz@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Mario', 'Jiménez Marset', 'mario.jimenezmarset@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Barbara', 'Jimenez', 'barbara.jimenez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Tomas', 'Santamaria', 'tomas.santamaria@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Aarón', 'García Anguita', 'aaron.garcia@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Óscar', 'Gómez Martin', 'oscar.gomez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Carlos', 'García Torregrosa', 'carlos.garciatorregrosa@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Monica', 'Delgado Capellan', 'monica.delgado@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alejandro', 'Robles Ruiz', 'alejandro.robles@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Carolina', 'Penalba Corpa', 'carolina.penalba@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Víctor', 'Castrillo Redondo', 'victor.castrillo@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Valentin', 'Preutesei', 'valentindanut.preutesei@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Abdessamad', 'Ammi', 'abdessamad.ammi@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'carlos', 'Serra Martínez', 'carlos.serra.martinez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Miguel', 'Marañón Quero', 'miguel.maranon@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Javier', 'Pérez Álvarez', 'javier.perezalvarez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Leonardo', 'Narvaez', 'leonardo.narvaez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Sergio', 'Pulido Salvador', 'sergio.pulido@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Hugo', 'Moreno Fernández', 'hugo.moreno@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Daniel', 'Serrano Real', 'daniel.serrano@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'David', 'Rubio Chavida', 'david.rubiochavida@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Pablo Adrian', 'Herrera Gomez', 'pabloadrian.herrera@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'ana cristina', 'borja parra ', 'anacristina.borja@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Daniel', 'García Valencia', 'daniel.garciavalencia@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Marta', 'Fraile Jara', 'marta.fraile@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Tsuen Kit', 'Lui Lin', 'tsuenkit.lui@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Hugo', 'De Argila Rivera', 'hugo.deargila@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Daniel', 'Mellado Vega', 'daniel.mellado@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Sergio', 'Simón Fernández', 'sergio.simon@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Eduardo', 'Corpa del Álamo', 'eduardo.corpa@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alejandro', 'Rodríguez Diego', 'alejandro.rodriguezdiego@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alvaro', 'Diez Morales', 'alvaro.diez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Carlos', 'Alonso', 'carlos.alonso@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Mario', 'Santana Antunes', 'mario.santana@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Samuel', 'Barahona Barrabino', 'samuel.barahona@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'María', 'Miguel Tolosana', 'maria.miguel@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alejandro', 'Ruiz García', 'alejandro.ruizgarcia@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alejandro', 'Cobo Marcos', 'alejandro.cobo@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Luis Miguel', 'Cañizares Diaz', 'Luismiguel.canizares@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alberto', 'Barbacid', 'alberto.barbacid@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alonso', 'García Martín', 'alonso.garcia@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Diego', 'Cardona Hernandez', 'diego.cardona@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Adrian', 'Jacek', 'adrian.jacek@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Héctor', 'Gil Fuertes', 'hector.gil@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Julio Alejandro', 'Ordoñez Rimacuna', 'julioalejandro.ordonez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Álvaro', 'Casco Valero', 'alvaro.casco@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Angel', 'Pinto Diaz', 'angel.pinto@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Raúl', 'García Muñoz', 'raul.garciamunoz@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Diego', 'Pérez Gregorio', 'diego.perez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Jorge', 'Rodríguez Alonso', 'jorge.rodriguezalonso@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alejandro', 'Navarro', 'alejandro.navarro@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Jose Antonio', 'López Pachón', 'joseantonio.lopez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Marta', 'Quirós Martín-Portugués', 'marta.quiros@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Pablo', 'Gonzalo Lucas', 'pablo.gonzalo@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Juan', 'Solís Torrijos', 'juan.solis@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Marcos', 'Pedroche Pérez', 'marcos.pedroche@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alberto', 'Rodriguez-Rey', 'alberto.rodriguez-rey@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Kevin Sebastián', 'Bayas Sarzosa', 'kevin.bayas@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alejandro', 'Cánovas López', 'alejandro.canovas@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Javier', 'Alonso Mansilla', 'javier.alonsomansilla@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Asil', 'Galan', 'asil.galan@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alejandro', 'Amores Fraile', 'alejandro.amores@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Ivan', 'Vazquez', 'ivan.vazquez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alumno', 'Test', 'alumnotest@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Marisol ', 'Bao ', 'marisol.bao@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Manuel', 'Diaz Bernal', 'Manuel.Diaz@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Marco ', 'Carrasco Talan', 'marco.carrasco@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Miguel', 'González Rubio', 'mangel.gonzalez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'JAVIER', 'VAZQUEZ', 'Javier.Vazquez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alfredo', 'Blanco Garcia', 'alfredo.blancogarcia@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Daniel', 'Pérez Diaz', 'daniel.perezdiaz@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Oscar', 'Lopez', 'oscar.lopezalcala@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Rodrigo', 'Ramírez López', 'rodrigo.ramirez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Luis', 'Infantes Lacal', 'Luis.infantes@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Cristian', 'Jimenez', 'cristianjavier.jimenez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Pedro', 'Álvarez', 'pedro.ruiz@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Elizabeth', 'Sáenz Camacho', 'elizabeth.saenz@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Julian', 'Calvo', 'julian.calvo@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Álvaro', 'Buiza', 'alvaro.buiza@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'sergio', 'navas', 'sergio.navas@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Salima', 'Agmir', 'salima.agmir@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Jorge', 'Mori Felipe', 'jorge.mori@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Arturo', 'Yañez Gomez', 'arturo.yanez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Giovanny ', 'Panesso Rodriguez', 'giovanny.panesso@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Daniel', 'Talavera Clemente', 'daniel.talavera@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Ruben', 'Gomez-Lobo Fuentes', 'ruben.gomez-lobo@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Jorge', 'Salas Rodriguez', 'jorge.salas@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Luis Andres', 'Martinez Berraquerro', 'luisandres.martinez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Heily Madelay', 'Ajila Tandazo', 'heilymadelay.ajila@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'David', 'Martínez Estébanez', 'david.martinezestebanez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Sofia', 'Rojas', 'sofia.rojas@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Gerson', 'Luque Huanca', 'gerson.luque@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Juan Jose', 'Rodríguez Baza', 'juanjose.rodriguez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Mario', 'García Romero', 'mario.garciaromero@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Lucian', 'Ciusa', 'lucianmarian.ciusa@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Andrews', 'Dos Ramos', 'andrews.dosramos@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Sergio', 'Jimenez', 'sergio.jimenezmartin@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Alvaro', 'Lopez Redondo', 'alvaro.lopezredondo@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Ángel', 'Toledo Rodelgo', 'angel.toledo@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Iñigo Samuel', 'Jiménez Montoro', 'inigosamuel.jimenez@tajamar365.com', 1, NULL, undefined);
INSERT INTO dbo.UsuariosMirror (Id, Nombre, Apellidos, Email, EstadoUsuario, Imagen, IdRole) VALUES (undefined, 'Sergio', 'Rincón De La Cruz', 'sergio.rincon@tajamar365.com', 1, NULL, undefined);

GO
